export default {
  SIGN_IN: '/api/v1/account/login',
  SIGN_UP: '/api/v1/account',
  INVITE_LINK: '/api/v1/users/invite_link',
  ACCOUNT_ME: '/api/v1/account/me',
  ORGANIZATIONS: '/api/v1/organizations',
  LOCALITIES: '/api/v1/localities',
  POLYGONS: '/api/v1/polygons',
  // LANDLORDS: '/api/v1/landlords',
  FIELDS: '/api/v1/fields',
  // AREAS: '/api/v1/areas',
  DEPARTMENTS: '/api/v1/departments',
  // CONTRACT: '/api/v1/contracts',
  // RENTERS: 'api/v1/renters',
  // EXCHANGE_ACTS: 'api/v1/exchange-acts',
  // FILES: 'api/v1/files',
};
